config/routes.rb
Rails.application.routes.draw do
  root to: 'top#index'
  devise_for :users,
    controllers: {
      registrations: :registrations,
      sessions: :sessions
    }

  resources :users, only: %i[index show]
  resources :reactions, only: %i[create]
  resources :matching, only: %i[index]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reaction.rb
# == Schema Information
#
# Table name: reactions
#
#  id           :bigint           not null, primary key
#  status       :integer          not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  from_user_id :bigint           not null
#  to_user_id   :bigint           not null
#
# Indexes
#
#  index_reactions_on_from_user_id  (from_user_id)
#  index_reactions_on_to_user_id    (to_user_id)
#
# Foreign Keys
#
#  fk_rails_...  (from_user_id => users.id)
#  fk_rails_...  (to_user_id => users.id)
#
class Reaction < ApplicationRecord

  belongs_to :to_user, class_name: "User"
  belongs_to :from_user, class_name: 'User'

  enum status: { like: 0, dislike: 1 }
  
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  avatar                 :string
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  gender                 :integer          default("man"), not null
#  name                   :string           not null
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  self_introduction      :text
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true
  validates :gender, presence: true
  validates :self_introduction, length: { maximum: 500 }

  has_many :reactions, dependent: :destroy

  mount_uploader :avatar, AvatarUploader

  enum gender: { man: 0, woman: 1 }

  def update_witout_current_password(params, *options)
    if params[:password].blank? && params[:password_confirmation].blank?
      params.delete(:password)
      params.delete(:password_confirmation)
    end

    result = update(params, *options)
    clean_up_passwords
    result
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  add_flash_types :success, :info, :warning, :danger

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name gender])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[name self_introduction avatar])
  end
end

app/controllers/matching_controller.rb
class MatchingController < ApplicationController
  before_action :authenticate_user!

  def index
    got_reaction_user_ids = Reaction.where(to_user_id: current_user.id, status: 'like').pluck(:from_user_id)
    @match_users = Reaction.where(to_user_id: got_reaction_user_ids, from_user_id: current_user.id, status: 'like').map(&:to_user)
    @user = User.find(current_user.id)
  end
end

app/controllers/reactions_controller.rb
class ReactionsController < ApplicationController
  before_action :authenticate_user!

  def create
    reaction = Reaction.find_or_initialize_by(to_user_id: params[:user_id], from_user_id: current_user.id)
    reaction.update(status: params[:status])
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  protected

  def update_resource(resource, params)
    resource.update_witout_current_password(params)
  end

  def after_update_path_for(resource)
    user_path(resource)
  end

  def after_sign_up_path_for(resource)
    users_path
  end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController

   protected

  def after_sign_in_path_for(resource)
    users_path
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
    
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.where.not(id: current_user)
    @user = User.find(current_user.id)
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | TinderClone
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = render 'shared/flash_messages'
    = yield

app/views/matching/index.html.slim
.matching-index-page
  = render 'shared/navbar'
  .matching
    p.matching-title.ml-3
      | メッセージ
    p.matching-num
      | マッチングした人数: #{@match_users.count} 人
    .matching__list
      - if @match_users.present?
        - @match_users.each do |user|
          .matching__person
            - if user.avatar.url.nil?
              .matching__person-default-img
            - else
              = image_tag user.avatar.url, class: 'matching__person-img'
            .matching__person-name
              = user.name

app/views/shared/_error_messages.html.slim
- if object.errors.any?
  #error_messages.alert-danger
    ul.mb-0
      - object.errors.full_messages.each do |msg|
        li= msg

app/views/shared/_flash_messages.html.slim
- flash.each do |message_type, message|
  div class=("alert alert-#{message_type}") = message

app/views/shared/_navbar.html.slim
nav.navbar.navbar-light
  = link_to users_path, class: 'nav-item nav-link', data: { turbolinks: false } do
    span class=('active' if current_page?(users_path))
      i.fas.fa-fire.fa-lg.inherit
  = link_to matching_index_path, class: 'nav-item nav-link' do
    span class=("active" if current_page?(matching_index_path))
      i.fas.fa-comments.fa-lg.inherit
  = link_to user_path(@user), class: 'nav-item nav-link' do
    span class=('active' if current_page?(user_path(@user)) || current_page?(edit_user_registration_path))
      i.fas.fa-user.fa-lg.inherit

app/views/top/index.html.slim
.jumbotron
  .container
    .navbar.navbar-light
      = link_to 'Tinder Clone', root_path, class: 'navbar-brand text-white'
      .navbar__sign-in-btn
        = link_to 'ログイン', new_user_session_path, class: 'btn my-2 my-sm-0 bg-light text-top-color'

  .top-title
    h1.text-white.text-center
      | Swipe Right

  .top-authentication.text-center
    .top-authentication__sign-up-btn.m-3
      = link_to 'アカウントを作成する', new_user_registration_path, class: 'btn text-white'
    .top-authentication__sign-in-btn.m-3
      = link_to 'ログイン', new_user_session_path, class: 'btn text-white'

app/views/users/_user.html.slim
.swipe--card id="#{user.id}"
  - if user.avatar.url.nil?
    .profile-default-img
  - else
    = image_tag user.avatar.url, class: 'profile-img'
  p.profile-name
    = user.name

app/views/users/index.html.slim
.user-index-page
  = render 'shared/navbar'

  .swipe
    .swipe--status
      i.fa.fa-times
      i.fa.fa-heart
    .swipe--cards
      = render @users
      .no-user
        | 近くにお相手がいません
    .swipe--buttons
      button#dislike
        i.fas.fa-times.fa-2x
      button#like
        i.fas.fa-heart.fa-2x

app/views/users/show.html.slim
.user-show-page
  = render 'shared/navbar'
  .profile.mt-4
    - if @user.avatar.url.nil?
      .profile-default-img
    - else
      = image_tag @user.avatar.url, class: 'profile-img'

    .profile-name.mt-4
      = @user.name
    .profile-text
      - if @user.self_introduction.present?
        = simple_format(@user.self_introduction)
      - else
        | 自己紹介...

  - if current_user.id == @user.id
    .user-action
      .user-action-common
        = link_to destroy_user_session_path, method: :delete do
          i.fas.fa-sign-out-alt.fa-2x
        span ログアウト
      .user-action-common
        = link_to edit_user_registration_path do
          i.fas.fa-pencil-alt.fa-2x
        span 情報を編集